{% set name = "imageio-ffmpeg" %}
{% set version = "0.4.0" %}
{% set sha256 = "21790a32a44bc49eef234fd6cfeb27c4d85dd9efa629747031cf8e1e062353d1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - ffmpeg    

test:
  imports:
    - imageio_ffmpeg

about:
  home: https://github.com/imageio/imageio-ffmpeg
  doc_url: https://github.com/imageio/imageio-ffmpeg
  dev_url: https://github.com/imageio/imageio-ffmpeg
  summary: FFMPEG wrapper for Python
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
