{% set name = "imageio-ffmpeg" %}
{% set version = "0.3.0" %}
{% set sha256 = "28500544acdebc195159d53a4670b76d596f368b218317bad5d3cbf43b00d6c2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - ffmpeg

test:
  imports:
    - imageio_ffmpeg

about:
  home: https://github.com/imageio/imageio-ffmpeg
  doc_url: https://github.com/imageio/imageio-ffmpeg
  dev_url: https://github.com/imageio/imageio-ffmpeg
  summary: FFMPEG wrapper for Python
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
