{% set name = "imageio-ffmpeg" %}
{% set version = "0.4.1" %}
{% set sha256 = "0ca618d19d9d7d8ed59f238d801a31a34d5cdf4dce2f00a6138f329e11cf4a04" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - ffmpeg

test:
  imports:
    - imageio_ffmpeg

about:
  home: https://github.com/imageio/imageio-ffmpeg
  doc_url: https://github.com/imageio/imageio-ffmpeg
  dev_url: https://github.com/imageio/imageio-ffmpeg
  summary: FFMPEG wrapper for Python
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
