travis:
  secure:
    BINSTAR_TOKEN: bgH69ijfkF5pmVSuglTfaTHXNSmFPj53Rjgse/BVESTTcBq+S2ioFMvPqQJp+ak9yXoFWjGrQ4Rjh5GFODsKfIgvegGiFcTwVMQ90ITKgzEX7mW9pVfwxzkCAfh4QGc+4/lJPYgmdwLlfhydSYaEj7tF1TgFfvmv5Jt2VT/vcwKla5OGSgs0Rgnf3b0dwDQuiZn+ohpV8jdN2XsbA625hG82/UCT6JSa4JLU3gkzgjIMQUr0rQWpDqiD/b70n3a6VBzYjmneSJyJ1hZVUA+4HM5W1QbmfSowa2bZKuzjOX85zfWrn9EnK6g96aanFDiEKDa4nBdTQCgZjNrqEc5IucpDQocFOULCPpGVK+xQtOjsxKAfJuGMmXGXjwsySUD+5PjOTvENLunAzJXsElds66+pdZfnQZcuy4/YJdmdy4BQ6Beh1fteRI5giRE1xAWmnDlbPf7C5fxp0cfUA4BDLCkbpst7U/A50Vqgm9iTzaqi+wm4p7U8rf0haiMvrurli99x8YiYAJH2j3KIKzwSFUFiJPZAYhmEkO3BqGAQG/DTlWMPK8GzFgjD57lJIsbe2RgDQABhzcYbcqq5ShAiNJ77E/lyU9fQ3dm304LTJZ4HmnLRfdFRTzJ7Skw2xdEtCELj0HFgD2LtL7wMQGeE+usrKWJNlR9rU4ovdBJY8X0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
